### PR TITLE
Integrate MSAK test

### LINKED ISSUE #63: Integrate msak-js as multi-stream option
Add option for multi-stream testing on speed.measurementlab.net by integrating msak-js. 

@stephen-soltesz @laiyi-ohlsen Do you imagine this to be the default option? Should there be a checkbox to enable multi-stream? Perhaps a transition period so users can report if something is not working as intended? I'm not planning to start working on this before next week, but your input here would be much appreciated. :)

### PR DESCRIPTION
**Pull request by robertodauria**
This PR integrates the MSAK javascript client and runs the MSAK test either before or after the ndt7 test (randomly, with a 50% probability for each option). 

The MSAK client is currently configured as an ndt7 test (10s, single BBR stream). This will provide easily comparable data to validate MSAK's throughput1 protocol and the server/client implementations.

Preview available at https://mlab-sandbox.web.app

Closes #63.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/mlab-speedtest/67)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-speedtest/67)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`app/measure/measure.html` line 49 at r1](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-NravFdVBDKAinBDAY7B:-NravFdVBDKAinBDAY7C:ba98krt) ([raw file](https://github.com/m-lab/mlab-speedtest/blob/6652b0a0916b91ff60532863cc05f87294129c39/app/measure/measure.html#L49)):*
We also discussed a simple message below the results signaling that we will run two tests back to back. Maybe something like:

> We are temporarily running two tests back to back to calibrate a new measurement protocol. This means results may take a little longer to appear than usual. Thank you for your help.
___
*[`app/measure/measure.js` line 189 at r1](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-NrarBUdDy9J-8YEBsa5:-NrarBUdDy9J-8YEBsa6:b-sz88q8) ([raw file](https://github.com/m-lab/mlab-speedtest/blob/6652b0a0916b91ff60532863cc05f87294129c39/app/measure/measure.js#L189)):*
> ```JavaScript
> function uuidv4() {
>   return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, c =>
>     (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
> ```

Please include a link to this: https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random) - the RFC did not help me recognize this as correct, (nor does the wiki link) but knowing that uuid v4 means random helps. I'm taking most of this logic on faith.

**Review by robertodauria — COMMENTED** [review]
PTAL again?

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-:-NreXKXb1QMJ0GQR8QkQ:bch9hor)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`app/measure/measure.html` line 49 at r1](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-NravFdVBDKAinBDAY7B:-NreXB7D47v2sv13JROw:b-896fix) ([raw file](https://github.com/m-lab/mlab-speedtest/blob/6652b0a0916b91ff60532863cc05f87294129c39/app/measure/measure.html#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We also discussed a simple message below the results signaling that we will run two tests back to back. Maybe something like:

> We are temporarily running two tests back to back to calibrate a new measurement protocol. This means results may take a little longer to appear than usual. Thank you for your help.
</blockquote></details>

Done.
___
*[`app/measure/measure.js` line 189 at r1](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-NrarBUdDy9J-8YEBsa5:-NreXC03Et1H-hAbQGF5:b-a2dt7t) ([raw file](https://github.com/m-lab/mlab-speedtest/blob/6652b0a0916b91ff60532863cc05f87294129c39/app/measure/measure.js#L189)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please include a link to this: https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random) - the RFC did not help me recognize this as correct, (nor does the wiki link) but knowing that uuid v4 means random helps. I'm taking most of this logic on faith.
</blockquote></details>

Done. Also, I've linked to the SO question that code comes from.

**Review by stephen-soltesz — APPROVED** [review]
Functional changes :lgtm:

A few suggestions about presentation.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-:-Nrep_Sh7CigXuo-HXHa:b8qwgg8)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[`app/measure/measure.html` line 35 at r2](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-NrepgcBCCGJ9lxvGNnG:-NrepgcBCCGJ9lxvGNnH:bdhrcg1) ([raw file](https://github.com/m-lab/mlab-speedtest/blob/ce1ed8503459a3450aaf4eafaf83bef9de8459d6/app/measure/measure.html#L35)):*
> ```HTML
>       </div>
>       </p>
>       <small>We are temporarily running two tests back to back to calibrate a new measurement protocol. This means
> ```

Can this be italics? Right now it blends into the rest of the page, people may not notice it.
___
*[`app/measure/measure.html` line 60 at r2](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-NreoymG-fz7v2CLiqBM:-NreoymG-fz7v2CLiqBN:bgw92xi) ([raw file](https://github.com/m-lab/mlab-speedtest/blob/ce1ed8503459a3450aaf4eafaf83bef9de8459d6/app/measure/measure.html#L60)):*
> ```HTML
>               <td></td>
>               <td>NDT</td>
>               <td>MSAK</td>
> ```

Should these be links to learn more? Do we have an msak page? Adding a link that will be populated could work too, e.g. https://www.measurementlab.net/tests/msak/

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-speedtest/67)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`app/measure/measure.html` line 35 at r2](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-NrepgcBCCGJ9lxvGNnG:-Nrf6q8DBa0ix9dmJanf:b-896fix) ([raw file](https://github.com/m-lab/mlab-speedtest/blob/ce1ed8503459a3450aaf4eafaf83bef9de8459d6/app/measure/measure.html#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can this be italics? Right now it blends into the rest of the page, people may not notice it.
</blockquote></details>

Done.
___
*[`app/measure/measure.html` line 60 at r2](https://reviewable.io/reviews/m-lab/mlab-speedtest/67#-NreoymG-fz7v2CLiqBM:-Nrf2t1y25sV-ZDSrj_7:b-kok5d7) ([raw file](https://github.com/m-lab/mlab-speedtest/blob/ce1ed8503459a3450aaf4eafaf83bef9de8459d6/app/measure/measure.html#L60)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should these be links to learn more? Do we have an msak page? Adding a link that will be populated could work too, e.g. https://www.measurementlab.net/tests/msak/
</blockquote></details>

Not a huge fan of introducing 404s, but the page is going to be there soon enough. I've added "?" with a link to the test description page.

**Pull request merged**
