### PR TITLE
app/services/mlabService.js: s/mlab-ns/locate/

### LINKED ISSUE #14: Please update to use locate.measurementlab.net
I have noticed with @bassosimone that in Iran `mlab-ns.appspot.com` does not work because of geo-blocking, while `locate.measurementlab.net` does. Please, update the website to use the latter, so Iranians can run NDT?

### PR DESCRIPTION
**Pull request by bassosimone**
Closes #14

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/mlab-speedtest/15)

### CODE REVIEW

**Comment by bassosimone** [comment]
(The build is broken, but it does not seem like I did break it.)

**Comment by critzo** [comment]
@bassosimone LGTM on the change, and I'll work on testing why the build fails before we merge.

**Comment by bassosimone** [comment]
Sure, I'll leave merging to you, if you don't mind! Thanks for the review!

**Comment by critzo** [comment]
Will do. Merge to master would trigger a failed build to production until we fix. Thanks for adding this @sbs!

**Pull request merged**
